stages:
  prepare_data:                               # Stage de preprocesamiento
    cmd: python src/prepare_data.py
    deps:
      - src/prepare_data.py
      - data/data.csv
      - params.yaml
    outs:
      - data/X_train.csv
      - data/X_test.csv
      - data/y_train.csv
      - data/y_test.csv

  train_model_optuna:                        # Stage de optimización de modelos
    cmd: python src/train_model_optuna.py
    deps:
      - src/train_model_optuna.py
      - data/X_train.csv
      - data/y_train.csv
      - data/X_test.csv
      - data/y_test.csv
      - params.yaml
    outs:
      - models/optuna/best_model_optuna.pkl
      - metrics/optuna_results.csv
      - metrics/optuna_study.pkl

  evaluate_model:                           # Stage evaluación de modelos
    cmd: python src/evaluate_model.py
    deps:
      - src/evaluate_model.py
      - data/X_test.csv
      - data/y_test.csv
      - models/
    outs:
      - metrics/results.csv


