general:
  dataset_path: "data/data.csv"      # Ruta al dataset
  target_column: "price"             # Nombre de la columna objetivo
  problem_type: "regression"         # Tipo de problema: "regression" o "classification"
  split_ratio: 0.2                   # Porcentaje de datos para el conjunto de prueba (20%)
  random_state: 42                   # Semilla para reproducibilidad
preprocess:
  numerical:                         # Lista de columnas numéricas
    - area
    - bedrooms
    - bathrooms
    - stories
    - parking
  categorical:                       # Lista de columnas categóricas
    - mainroad
    - guestroom
    - basement
    - hotwaterheating
    - airconditioning
    - prefarea
    - furnishingstatus
  scaling: "StandardScaler"          # Tipo de escalado: "StandardScaler", "MinMaxScaler", etc.
  encoding: "OneHotEncoder"          # Tipo de codificación para variables categóricas: "OneHotEncoder", "LabelEncoder"
optuna:
  n_trials: 500                      # Número de iteraciones para la optimización
  direction: "minimize"              # Objetivo de la optimización
  study_name: "auto_ml_optimization" # Nombre del estudio

# Hiperparámetros de los modelos
hyperparameters:
  RandomForest:
    n_estimators:
      min: 20
      max: 500
      step: 10
    max_depth:
      min: 5
      max: 20
      step: 1
  GradientBoosting:
    n_estimators:
      min: 20
      max: 500
      step: 10
    learning_rate:
      min: 0.01
      max: 0.1
      log: true
    max_depth:
      min: 5
      max: 20
      step: 1
  CatBoost:
    iterations:
      min: 20
      max: 500
      step: 10
    learning_rate:
      min: 0.01
      max: 0.1
      log: true
    depth:
      min: 5
      max: 16
      step: 1
  LinearRegression:
    fit_intercept: [ true, false ]
    alpha:
      min: 0.0
      max: 1.0
      step: 0.05
